#!/bin/sh
bspc rule -r "*"

# Autostart
poly-launch &

###---MONITORS---###
bspc monitor LVDS-1 -d 一 二 三 四 五 六 七 八 九

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 35
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 3
bspc config window_gap 10

bspc config normal_border_color	  "#23B3A7"
bspc config active_border_color	  "#1e1e1e"
bspc config focused_border_color  "#EC91B2"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color   "#dd2727"

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Lxappearance state=floating layer=above
